### ISSUE TITLE
Template parse error: unexpected "title" in block clause

### ISSUE THREAD

**Issue by xDarkicex** [Joker/jade#11]
each is undefined, for is undefined when trying to do functions in pug template.

**Comment by Joker** [comment]
Can you show me not working parts of that template?

**Comment by xDarkicex** [comment]
https://gist.github.com/xDarkicex/13204e6d61a8174d352641c4e4fe923b

The commented out parts are the broken Bits, I have included the render go code if I m=am doing this wrong.

**Comment by Joker** [comment]
Here's a [working example](https://github.com/Joker/jade/tree/issue11/example/jade_extends) with `includes` and `extends`.
You can implement and attach other Funcs the same way.
If you uncomment an `extends` in [Gist/index.pug](https://gist.github.com/xDarkicex/13204e6d61a8174d352641c4e4fe923b#file-index-pug-L1) the blocks will work.

**Comment by xDarkicex** [comment]
I had too add a "." to all my var from my object and my each in func didnt work but range did, seems your engine doesn't 100% convert jade too go templates I had to sort of mix and match the two to get it working properly.

**Comment by Joker** [comment]
At this moment the engine 100% converts from Jade to Go Template. So Javascript code works as is only if it's emulated on FuncMap, because Go Template does not support such constructions as 'each', 'unless' etc.

**Comment by xDarkicex** [comment]
I see, I got it all figured out now thank you, now that I understand I see why the funcmap is needed, I might suggest covering custom functions in your example and or possibly mentioning it in the readme.
Thank you for your time.

**Comment by Joker** [comment]
Ok, it's a good idea, thank you.
