### ISSUE TITLE
Engine doesn't recognize model objects 

### ISSUE THREAD

**Issue by oscarryz** [Joker/jade#12]
I tried the most basic template in pug's getting started guide: 

https://pugjs.org/api/getting-started.html

    p #{Name}'s Pug source code!

But the generated go template doesn't define the property which results in the error:

    panic: template: index:2: function "Name" not defined

Similar things happen with "include" ( and probably other basic Pug/Jade functionality) 

I can workaround it by naming the variable as `.Name`  or even use Go template syntax `{{.Name}}` but then it becomes an "invalid" Jade/Pug template. 

Question: Is this just a package to parse Jade files? Or it is expected to work as a Jade/Pug engine to create valid Go templates?

Here's an example of the input and along with a very basic nodejs app doing the same work.
 
https://gist.github.com/anonymous/52dfd36d6c3d09df60b1d1ba6d68b81c

Kudos for the work so far!

**Comment by xDarkicex** [comment]
Same line of issue I was having.
https://github.com/Joker/jade/issues/11

You see this works by turning the pug template into a Go template and go templates doesn't support builtin JavaScript also things in Go templates need "." If you want a function you have to make a funcmap.
This engine turns the pug into Go template so all functions need to work ultimately as a Go template.

**Comment by Joker** [comment]
I agree with the @xDarkicex.

**Comment by oscarryz** [comment]
I understand how the implementation works, that's not the issue. but the fact the library doesn't fully supports Jade syntax where an object exists in the model and then can be consumed in the template. 

I'm ok with the closing of this ticket regardless. I was looking for a way to migrate some existing code base from node to go a while ago.

Thanks.

**Comment by Joker** [comment]
I've made a new version 1.0
It supports all syntax pug2 except of JavaScript functionality.
I'm going to replace JavaScript functionality with Golang so this code will work then:
`- Name := "John"`
`p #{Name}'s Pug source code!`

**Comment by treeder** [comment]
This really isn't proper pug syntax which makes it not really pug. Can't even seem to declare pug variables and use them.
