### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by jeevatkm** [Joker/jade#18]
Hello @Joker - I'm the author of [aah framework](https://aahframework.org). As aah user asked for Jade (pug) integration. I'm gonna a create integration elements here https://github.com/aah-cb/ve-pug under MIT for aah framework.

I thought to inform you and get your thoughts. Thank you.

**Comment by jeevatkm** [comment]
@Joker Also could you please tag and make a release as per https://semver.org?

Thanks again.

**Comment by jeevatkm** [comment]
@Joker I thought to inform you. Jade engine successfully integrated with aah `v0.10` release. `aah` user gets an option to choose view engine via aah CLI when they create new application.

Also thank you for tagging it.

**Comment by Joker** [comment]
I'm happy you found jade package useful.
You can also try new version [here](https://github.com/Joker/jade/tree/v1.0-pre)
