### ISSUE TITLE
How to pass current view context to child/include template 

### ISSUE THREAD

**Issue by jeevatkm** [Joker/jade#19]
@Joker I was trying your example program (https://github.com/Joker/jade/blob/master/example/jade.go) to see; how to integrate Jade library with aah framework. 

I have observed following, please let me know. Am I understood correctly?

1. ~~`<title>{{ pageTitle }}</title>` is not valid go template syntax. Valid one is `<title>{{ .pageTitle }}</title>`~~
2. ~~And if condition too `{{ if youAreUsingJade }}`, valid one is `{{ if .youAreUsingJade }}`. Basically `dot` is missing before variable~~
3. And pass on current context to child/sub template too; with dot notation like `{{ template "withGo" . }}` instead of `{{ template "withGo" }}`

Looking forward to your response.

**Comment by hengestone** [comment]
Why does it have to be valid go template syntax? These are jade templates, with go expressions.

**Comment by jeevatkm** [comment]
@hengestone @Joker Yesterday I learned to use this library and Jade/Pug syntax. My understanding is -
* We define templates in Jade (pug) form/syntax
* Jade library transforms Jade template into Go Template

So I have tried given examples to see the behavior. 

As you know, In Go template we define -
* For template context variable with dot notation -> `{{ .pageTitle }}`
* For template functions just mention function name ->`{[ pageTitle }}`
* While including child/another template, for passing current context value; we have to use dot notation -> `{{ template "withGo" . }}`

----

Last night, I have tried further after submitting this issue and I was able to sorted out first 2 points and understood better. So we are good on first 2 points. Just updated this issue with strikethrough.

However, issue no. 3 remains. If you have an understanding please guide me.

Issue details:

When we define `mixin` and mention like this `+ withGo` in the Jade template. Library produce this `{{ template "withGo" }}`; it is certainly a valid syntax. However it doesn't pass current view context variable to template `withGo`. Becuase for that syntax have to be with dot notation at the end `{{ template "withGo" . }}`

**Comment by jeevatkm** [comment]
May be I'm missing some piece of details to understand!!!

**Comment by jeevatkm** [comment]
This example: https://github.com/Joker/jade/tree/master/example/jade_extends produces go template with passing view context further. 

```html
<!DOCTYPE html>                         
<html>                                  
    <head>                              
        {{ block "title" . }}           
            <title>Default title</title>
        {{ end }}                       
    </head>                             
    <body>                              
        {{ block "content" . }}         
        {{ end }}                       
    </body>                             
</html>                                 
```

This is suppose to happen for mixin too `+ withGo` => `{{ template "withGo" . }}`

**Comment by Joker** [comment]
You haven't  to do it now.
At version 1.0 `mixin`, `include` and `extend` works directly with no translation into the Go templates.

**Comment by jeevatkm** [comment]
@Joker I will give it try and get back to you. Thank you.
