### ISSUE TITLE
Why LeftDelim and RightDelim is removed on master, is it moved?

### ISSUE THREAD

**Issue by jeevatkm** [Joker/jade#21]
Hello @Joker  - I'm using these options to supply user config for template delimiter. Why `LeftDelim` and `RightDelim` is removed on master, is it moved? I have checked the Go doc, couldn't find a reference.

Could you please added an option?

```
# github.com/aah-cb/ve-pug
../../github.com/aah-cb/ve-pug/pug.go:98:2: undefined: jade.LeftDelim
../../github.com/aah-cb/ve-pug/pug.go:99:2: undefined: jade.RightDelim
../../github.com/aah-cb/ve-pug/pug.go:137:2: undefined: jade.LeftDelim
../../github.com/aah-cb/ve-pug/pug.go:138:2: undefined: jade.RightDelim
../../github.com/aah-cb/ve-pug/pug.go:201:2: undefined: jade.LeftDelim
../../github.com/aah-cb/ve-pug/pug.go:202:2: undefined: jade.RightDelim
````

**Comment by Joker** [comment]
These options are deprecated and removed. You can use vars in `config.go` instead of it.

**Comment by jeevatkm** [comment]
@Joker Thanks, I will give it a try on vars and get back to you.
