### ISSUE TITLE
Integration with aah framework is broken

### ISSUE THREAD

**Issue by jeevatkm** [Joker/jade#22]
Hello @Joker - With `v0.10` release I have integrated the Jade library with aah framework go-aah/aah#171. 

I was able to achieve aah `views` directory structure with your previous version along with own `include` template function. Please you have a look on library located at https://github.com/aah-cb/ve-pug

aah views directory structure:
```
├── common
│   ├── error_footer.pug
│   ├── error_header.pug
│   ├── footer_scripts.pug
│   └── head_tags.pug
├── errors
│   ├── 404.pug
│   └── 500.pug
├── layouts
│   └── master.pug
└── pages
    └── app
        └── index.pug
```

`pages` directory would contain subdirectories (including nested directories) for each controller and its namespace. And each `action` would have respective template file in the directory.

More about aah views: https://docs.aahframework.org/views.html

----

Looking forward to your support to make the integration work again, thanks.

**Comment by omeid** [comment]
This issue has nothing to do with Jade. Please stop spamming.

**Comment by jeevatkm** [comment]
@omeid My goal is to make the integration work and seeking for support. NOT SPAMMING. NOT BLAMING, I hope you have read above detailed description. Do you think asking help is spamming?

With **latest Jade improvements**, I'm missing following elements -

* Template delimiter option (not sure how much is relevant with latest changes, may be taken care automatically, I don't know)
* `include` function is now handled within library so it will look for relative path for referred file unlike previous version I was managing source location externally.

Right now I'm working on this, not just create an issue and toss it aside. I request you please not to make a quick judgement.

**Comment by jeevatkm** [comment]
@omeid BTW I have informed here before I began my work please refer here #18 Keeping informed is important. Thank you.

**Comment by omeid** [comment]
If you require any specific functionality please open an issue outlining your requirement, better yet, create a pull request for that. This issue as standards is nothing far from spam.

People watch projects because they have an interest in the project, spamming those people with a constant stream of notifications about peripheral concerns is annoying.

**Comment by jeevatkm** [comment]
> People watch projects because they have an interest in the project

I completely agree.

----

Let me give a problem insights.  

* Template Delims was exists before refer to this tag https://github.com/Joker/jade/blob/v0.7.0/config.go#L14-L17 now it does not exists in master
* Include functions was not exists before its handled externally, refer to this example on tag https://github.com/Joker/jade/blob/v0.7.0/example/jade_include/main.go#L22-L35 now it exists with library

So above difference affected the downstream library. 

Given situation, Would you just jump on creating PR or Requesting feature or Get an thought process of author via available medium before reaching a conclusion.
