### ISSUE TITLE
Not support multi classes?

### ISSUE THREAD

**Issue by yeh19921026** [Joker/jade#26]
jade:

`nav.navbar.navbar-expand-md`

render:

`<nav class="{{ print " navbar " " " "navbar-expand-md " }}"></nav>`

It should:

`<nav class="navbar navbar-expand-md"></nav>`

**Comment by Joker** [comment]
`<nav class="{{ print " navbar " " " "navbar-expand-md " }}"></nav>` is the same as `<nav class="navbar navbar-expand-md"></nav>`  but after go template applied
