### ISSUE TITLE
Error: expected ';', found ','

### ISSUE THREAD

**Issue by speedwheel** [Joker/jade#27]
I have this file (index.jade), and when I run `jade -pkg=main index.jade`, I get the following error:
`index.jade.go:15:26: expected ';', found ','`

index.jade
```go
:go:func Index(title string)
p hello world
```

How can I make it work?

**Comment by Joker** [comment]
Can you show me your `index.jade.go` file you've got after you've run `jade -pkg=main index.jade` command?
hope you didn't edit this file after that :)

**Comment by speedwheel** [comment]
@Joker Hello, it doesn't create any `index.jade.go`, probably because of the error.
If I delete the `p` tag, then it works, for example:
index.jade:
```go
:go:func Index(title string)
```
This works, and it generates `index.jade.go`:
```go
// Code generated by "jade.go"; DO NOT EDIT.

package main

import (
	pool "github.com/valyala/bytebufferpool"
)

const ()

func Index(title string, buffer *pool.ByteBuffer) {

}
```
Any tips?

**Comment by speedwheel** [comment]
Also if I write this (like how is it's in the documentation), it doesn't work:
```go
:go:func(arg) (world string, second string)
p hello from page #{world}
```

But if I change it to this, it works:
```go
:go:func(arg) world string, second string
p hello from page #{world}
```

**Comment by Joker** [comment]
It happened because of Window's new line symbol (CR+LF) appeared instead of unix LF. I've fixed this bug. Now it should work correctly. Try again please.
