### ISSUE TITLE
Support for extends with codegen

### ISSUE THREAD

**Issue by terribleplan** [Joker/jade#28]
When trying to use the command line codegen tool I cannot find a way to satisfactorily use `extends`. I need to specify different params to each page so would like to to do something like:

layout.pug:
```
doctype html
html(lang="en")
  head
    title example
  body
    block content

```

page.pug:
```
extends ./layout

:go:func RenderPage(data string)

block content
  p=data
```

This fails with

`jade: jade.New(path).Parse():  template:3: Only import, named blocks and mixins can appear at the top level of an extending template`

Is there some other way of structuring templates to get the desired outcome? Is it not yet possible outside of manually using `ParseFile("page.jade")` inline?

**Comment by Joker** [comment]
```
extends ./layout

block content
    :go:func RenderPage(data string)
    p=data
```
This will work.
It doesn't matter where :go filter is located.
It will work at any nesting level.

**Comment by Joker** [comment]
When you use jade.go as library :go filter is not needed.
This filter is used as helper for command line tool (to set function name and parameters).

**Comment by terribleplan** [comment]
Putting the `:go:func` at another level was something I didn't even consider, and was exactly what I was looking for. Thanks!
