### ISSUE TITLE
I want to make the Frontend developer use pug in frontend . Then use Joker/jade transtering the pug to tpl for golang .

### ISSUE THREAD

**Issue by jerryniepan** [Joker/jade#30]
In https://github.com/Joker/jade/blob/master/testdata/v2/attributes.tpl

how to use for golang below?
    1. {{/* url = "https://example.com/" */}}  // line 19 
    2. <a class="{{ print currentUrl == "/" ? "active" : "" }}" href="/">Home</a> // line 41

**Comment by jerryniepan** [comment]
I want to make the Frontend developer use pug in frontend . Then use Joker/jade transter the pug to tpl for golang .

**Comment by Joker** [comment]
Variables work only in compile to Golang code mode.

In https://github.com/Joker/jade/blob/master/testdata/v2/attributes.go
```Go
url = "https://example.com/" // line 30
buffer.WriteString(`<a href="`)
WriteEscString(url, buffer)
buffer.WriteString(`">Another link</a>`)
```
