### ISSUE TITLE
Don't change current working dir when parsing template

### ISSUE THREAD

**Issue by pilvy** [Joker/jade#33]
In `parseSubFile()`, `os.Chdir()` is called to parse the template more easily. I suggest refactoring this function to not affect the process' working environment.

**Comment by kataras** [comment]
Hi @pilvy, this is a serious issue and bad design, we've just found it when using [iris](https://github.com/kataras/iris). See https://github.com/kataras/iris/issues/1450.

I am preparing a fork to solve that, probably push a PR too.

**Comment by kataras** [comment]
Fixed on https://github.com/Joker/jade/pull/34
