### ISSUE TITLE
Mixin args

### ISSUE THREAD

**Issue by redradrat** [Joker/jade#36]
I think the issue mentioned in #24 might actually not be fixed yet. Despite 4710ad0.

Taking a look at the .tpl testdata here:
https://github.com/Joker/jade/blob/ee26e3c533bb76832dc786941a44133e4af33e12/testdata/v2/mixins.tpl#L11-L17

The usage should read `{{ $name }}`, right? Now assuming the testdata is just not proper here, would that maybe hide the implementation issue here? I'd love to dig in myself, but I have a hard time visualising the code unfortunately...

**Comment by redradrat** [comment]
I assume it's because in here: https://github.com/Joker/jade/blob/ee26e3c533bb76832dc786941a44133e4af33e12/jade_node.go#L424-L435

code__buffered is used, which does not construct the buffer with a $ reference.

https://github.com/Joker/jade/blob/ee26e3c533bb76832dc786941a44133e4af33e12/config.go#L33

But then, I think this means, all variable references are just simply lacking the $ denotation?

**Comment by Joker** [comment]
Simple way to solve the problem with mixin in .tpl case
Is to add dollar sign to `name` variable
```pug
mixin pet(name)
  li.pet= $name

ul
  +pet('cat')
```
will be translated into
```html
<ul>{{ $name := "cat" }} 
    <li class="pet">{{ $name }}</li>
</ul>
```

**Comment by redradrat** [comment]
Yeah I found that workaround too... but that's breaking with pug variable calls then, isn't it?

**Comment by Joker** [comment]
if you want backward compatibility with pug
edit  jade/config.go (Line 47)
```go
mixin__var = "{{ %s := %s }}"
```
the code below will also work on pug.js
```pug
mixin pet($name)
  li.pet= $name
```

**Comment by redradrat** [comment]
That'll work. Thanks!
