### ISSUE TITLE
go get not working on Ubuntu 

### ISSUE THREAD

**Issue by kargirwar** [Joker/jade#38]
OS: Ubuntu 20.04.1 LTS

go get github.com/Joker/jade/cmd/jade
go: downloading github.com/Joker/jade v1.0.0
go get: module github.com/Joker/jade@upgrade found (v1.0.0), but does not contain package github.com/Joker/jade/cmd/jade

**Comment by tbo** [comment]
I ran into the same issue. It seems that the latest tagged version (v1.0.0) didn't contain `/cmd/jade`. Getting the master version worked though:
`go get github.com/Joker/jade/cmd/jade@master`

**Comment by candlerb** [comment]
FYI, I see the same on macOS

```
MacBook-Pro-4:~ $ go get github.com/Joker/jade/cmd/jade
go: downloading github.com/Joker/jade v1.0.0
go get: module github.com/Joker/jade@upgrade found (v1.0.0), but does not contain package github.com/Joker/jade/cmd/jade
MacBook-Pro-4:~ $ go version
go version go1.16.3 darwin/amd64
```

If the package is behaving as expected, then i think the installation instructions [here](https://github.com/Joker/jade#installation) need fixing.

**Comment by candlerb** [comment]
`git diff v1.0.0 master` shows that `jade/cmd/*` wasn't introduced until after v1.0.0.  Would releasing a v1.0.1 fix this?

**Comment by thejimmyg** [comment]
Same issue here. Without the `jade` command you can't compile your templates.

This worked for me on macOS 10.15 with go 1.16:

```
go get github.com/Joker/jade/cmd/jade@master
export PATH="$PATH:${HOME}/go/bin"
go mod download github.com/Joker/hpp
go mod download github.com/valyala/bytebufferpool
go generate
```

I also found that `tpl_hello` from the README.md needed to be renamed `Jade_hello` for the example to run.

**Comment by Joker** [comment]
Thank you all. (tag added)
