### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by kataras** [Joker/jade#6]
Hello @Joker I'm the author of the [Iris](https://github.com/kataras/iris) I wanted you to know that I'm going to add build'n support  for your template engine. But before that I want to know if you are willing to develop this package for a long time more

**Comment by Joker** [comment]
Hi @kataras Yes, I'm going to develop and support it further because i use it myself at production

**Comment by kataras** [comment]
I'm happy about this, when I finish the transaction I will add your project in the readme, if you want add a section with 'packages are using Jade' and add Iris to it, it will help your project's ranks also :)

**Comment by Joker** [comment]
What do you mean by  ```.Funcs``` ? Would you please show any not working example to let me see the problem?  
(leftDelim, rightDelim You can set in config.go)

**Comment by kataras** [comment]
With .Funcs I mean the html/template.FuncMap , I saw the left,right delims but they are constants, do you want to fork your project? I want to use it directly from your repository

**Comment by Joker** [comment]
>How .Funcs works with this engine?

```go
package main

import (
	"os"
	"strings"
	"text/template"
	"github.com/Joker/jade"
)

func main() {
	funcMap := template.FuncMap{ "myFunction": strings.Title }

	jade_tpl, _ := jade.Parse("jt", `!!! 5: html: body: p {{myFunction "something"}}`)
	tpl, _ := template.New("titleTest").Funcs(funcMap).Parse(jade_tpl)
	tpl.Execute(os.Stdout, "")
}
```
stdout:
```html
<!DOCTYPE html>
<html>
    <body>
        <p>Something</p>
    </body>
</html>
```

**Comment by kataras** [comment]
I'm doing the same thing excactly, what am I missing? let me check again

**Comment by kataras** [comment]
I have a func named render
```go
//...
"render": func(fullPartialName string) (template.HTML, error) {
			buf, err := s.executeTemplateBuf(fullPartialName, binding)
			// Return safe HTML here since we are rendering our own template.
			return template.HTML(buf.String()), err

		}//....
```

the page.jade
```html
doctype html
html(lang=en)
	head
		meta(charset=utf-8)
		title Title
	body
	   {{ render "partials/partialPage.jade"}}
		p ads
		ul
			li The name is {{.Name}}.
			li The age is {{.Age}}.

		range .Emails
			div An email is {{.}}

		with .Jobs
			range .
				div.
				 An employer is {{.Employer}}
				 and the role is {{.Role}}

```
the partials/partialPage.jade
```html
div.
Something different


```
The error  on runtime when execute the template:

`template: page.jade:9:12: executing "page.jade" at <render>: wrong number of args for render: want 0 got 1`

The browser -> view source
```html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Title</title>
    </head>
    <body>
        
```

**Comment by Joker** [comment]
I didn't get an error like you.
I've made for you a [working example](https://github.com/Joker/jade/tree/master/example/jade_include) with your use case. May be it will help you.
