### ISSUE TITLE
support for "block content" in templates

### ISSUE THREAD

**Issue by p4tin** [Joker/jade#7]
In jade you can create a template file and they use "block content" in the template and then in the partials you simply say:

extends layout
block content

and everything in the block content is added to the template to produce the html page. This does not appear to be supported or perhaps I just need an example on how to use it ???

**Comment by Joker** [comment]
Example in [github.com/Joker/jade/example/jade_extends](https://github.com/Joker/jade/tree/master/example/jade_extends).
